package CORBATest;

/**
* CORBATest/EchoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from echo.idl
* 7 окт€бр€ 2022 г. 16:54:27 YEKT
*/

public final class EchoHolder implements org.omg.CORBA.portable.Streamable
{
  public CORBATest.Echo value = null;

  public EchoHolder ()
  {
  }

  public EchoHolder (CORBATest.Echo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CORBATest.EchoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CORBATest.EchoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CORBATest.EchoHelper.type ();
  }

}
