package CORBATest;


/**
* CORBATest/EchoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from echo.idl
* 7 окт€бр€ 2022 г. 16:54:27 YEKT
*/

public interface EchoOperations 
{
  String echoString (String msg);
  String echoReversedString (String msg);
} // interface EchoOperations
