package CORBATest;


/**
* CORBATest/EchoPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from echo.idl
* 7 окт€бр€ 2022 г. 16:54:27 YEKT
*/

public abstract class EchoPOA extends org.omg.PortableServer.Servant
 implements CORBATest.EchoOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("echoString", new java.lang.Integer (0));
    _methods.put ("echoReversedString", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CORBATest/Echo/echoString
       {
         String msg = in.read_string ();
         String $result = null;
         $result = this.echoString (msg);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // CORBATest/Echo/echoReversedString
       {
         String msg = in.read_string ();
         String $result = null;
         $result = this.echoReversedString (msg);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CORBATest/Echo:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Echo _this() 
  {
    return EchoHelper.narrow(
    super._this_object());
  }

  public Echo _this(org.omg.CORBA.ORB orb) 
  {
    return EchoHelper.narrow(
    super._this_object(orb));
  }


} // class EchoPOA
