package CORBATest;


/**
* CORBATest/Echo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from echo.idl
* 7 окт€бр€ 2022 г. 16:54:27 YEKT
*/

public interface Echo extends EchoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Echo
