module CORBATest
{
	struct Person
	{
		string Name;
		string Surename;
		string Patronymic;
	};

	typedef sequence<Person> PersonSeq;


	interface Echo
	{
		void reverseString(inout PersonSeq persons);
	};
};